### ISSUE TITLE
I cannot get this to work. 

### ISSUE THREAD

**Issue by Lorfa** [THeK3nger/obsidian-goban#4]
I've downloaded the release files, placed them in a directory in the folder for plugins, activated the plugin and received no errors. However when I make a note in a code block with a valid position in Sensei's library format, nothing happens. This is on Windows 10. 
Can you provide instructions for installation and use? 

This is with Obsidian 1.4.12. 
![Goban1](https://github.com/THeK3nger/obsidian-goban/assets/12265183/572f3338-9030-4194-8239-c80b47979f7b)
![Goban2](https://github.com/THeK3nger/obsidian-goban/assets/12265183/2672c11b-b224-4ca9-b4e9-57c669768f1c)

**Comment by THeK3nger** [comment]
Hi!

Did you write `goban` as the code block language?

This is what it should look like (note the `goban` after the three ```)

````
```goban
$$ A [joseki] variation
$$ -------------------
s$ | . . . . . . . . .
$$ | . . . . . . . . .
$$ | . . 7 3 X d . . .
$$ | . . 0 1 0 6 . . .
$$ | . . 4 2 5 c . . .
$$ | . . 8 X a . . . .
$$ | . . . b . . . . .
$$ | . . . . . . . . .
$$
$$ [2| Nadare Joseki]
$$ [C|#1]
```
````

**Comment by Lorfa** [comment]
Thanks for replying so quickly. It works!

![TYObsidian](https://github.com/THeK3nger/obsidian-goban/assets/12265183/73eb15f8-4de9-401f-ad47-7dfc06a4246e)
